# Generated by Django 3.2.5 on 2021-07-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('department', models.CharField(choices=[('cse', 'Cse'), ('eee', 'Eee')], default='cse', max_length=3)),
                ('year', models.PositiveIntegerField(default=0, verbose_name='Year')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('student_id', models.CharField(max_length=255, verbose_name='Student ID')),
                ('photo_url', models.URLField(verbose_name='Photo')),
                ('phone', models.CharField(max_length=128, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
