# Generated by Django 3.2.5 on 2021-07-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('cover_image_url', models.URLField(verbose_name='Cover Image URL')),
                ('date', models.DateTimeField(verbose_name='Date Time')),
            ],
            options={
                'unique_together': {('title', 'description', 'cover_image_url', 'date')},
            },
        ),
    ]
